version: '3'

services: 
  api:
    build: ./api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment: 
      - PORT=3000
      - MONGO_URL=mongodb://api_mongo:27017/api
    depends_on: 
      - api_mongo

  api_mongo:
    image: mongo:4.4.8
    volumes:
      - mongoData:/data/db

volumes: 
  mongoData:

